name: Python Action Build & Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  # Run the tests on all supported versions of Python
  testing:
    uses: advanced-security/reusable-workflows/.github/workflows/python-testing.yml@v0.2.0
    secrets: inherit
    with:
      versions: "3.9,3.10,3.11,3.12,3.13"

  # Vendor the dependencies into the repository if needed
  vendoring:
    uses: advanced-security/reusable-workflows/.github/workflows/python-vendor.yml@v0.2.0
    needs: [testing]
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

  # Release a new version of the package
  release:
    uses: advanced-security/reusable-workflows/.github/workflows/python-release.yml@v0.2.0
    needs: [testing]
    secrets: inherit

  action-test:
    runs-on: ubuntu-latest
    needs: [testing]

    steps:
      - uses: actions/checkout@v4
      - name: Run action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
